### ISSUE TITLE
Could not pass event PlayerChangedWorldEvent to PerWorldInventory - IllegalArgumentException: Invalid inventory size; expected 27 or less

### ISSUE THREAD

**Issue by mibby** [EbonJaeger/perworldinventory-kt#187]
**Describe the bug**
```
[08:20:58] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to PerWorldInventory v2.3.2
java.lang.IllegalArgumentException: Invalid inventory size; expected 27 or less
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory.setContents(CraftInventory.java:85) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at me.ebonjaeger.perworldinventory.data.ProfileManager.transferInventories(ProfileManager.kt:147) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager.applyToPlayer(ProfileManager.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager.getPlayerData(ProfileManager.kt:100) ~[?:?]
	at me.ebonjaeger.perworldinventory.listener.player.PlayerChangedWorldListener.onPlayerChangedWorld(PlayerChangedWorldListener.kt:106) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor248.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:813) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:800) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at com.earth2me.essentials.paperlib.features.asyncteleport.AsyncTeleportPaper.lambda$teleportAsync$0(AsyncTeleportPaper.java:16) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.execute(IAsyncTaskHandler.java:89) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1143) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1086) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1100) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:619) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1161) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1144) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1120) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:963) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**To Reproduce**
* Player changed worlds by warping with ``/warp creative``.

**Expected behavior**
No error.

**Plugin version**
- [x] Using the latest released version of the plugin
- [ ] Using the `legacy` jar

Perworldinventory-kt-2.3.2.jar

**Server version**
Tuinity dev 92 (Paper Fork - Spigot 1.15.2)

**Additional context and logs**

I separate my inventory into two groups. I assume he went from group 1 to group 2.
```
groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    - spawn
    - void
    default-gamemode: SURVIVAL
    respawnWorld: spawn
  creative:
    worlds:
    - creative
    default-gamemode: CREATIVE
    respawnWorld: spawn
```

**Comment by mibby** [comment]
@EbonJaeger No possible quick hot-fix for this problem? :(

```
[13:21:12] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to PerWorldInventory v2.3.2
java.lang.IllegalArgumentException: Invalid inventory size; expected 27 or less
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory.setContents(CraftInventory.java:85) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at me.ebonjaeger.perworldinventory.data.ProfileManager.transferInventories(ProfileManager.kt:147) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager.applyToPlayer(ProfileManager.kt:128) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager.getPlayerData(ProfileManager.kt:100) ~[?:?]
	at me.ebonjaeger.perworldinventory.listener.player.PlayerChangedWorldListener.onPlayerChangedWorld(PlayerChangedWorldListener.kt:106) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor235.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:816) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:799) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at com.sekwah.advancedportals.bukkit.destinations.Destination.warp(Destination.java:141) ~[?:?]
	at com.sekwah.advancedportals.bukkit.destinations.Destination.warp(Destination.java:108) ~[?:?]
	at com.sekwah.advancedportals.bukkit.portals.Portal.activate(Portal.java:506) ~[?:?]
	at com.sekwah.advancedportals.bukkit.listeners.Listeners.checkTriggerLocations(Listeners.java:136) ~[?:?]
	at com.sekwah.advancedportals.bukkit.listeners.Listeners.onMoveEvent(Listeners.java:109) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor202.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1294) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
	at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
	at xuan.cat.XuanCatAPI.code.b.c.a.g.a(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1161) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1154) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1130) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:973) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```
