### ISSUE TITLE
Unknown error that fills console

### ISSUE THREAD

**Issue by samcarsonx** [EbonJaeger/perworldinventory-kt#69]
I don't know what it's doing but the console is filled with it, I run Spigot 1.12.2
```
> [12:21:03 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.1.0 generated an exception while executing task 212
java.lang.NoSuchFieldError: PLAYER_HEAD
at me.ebonjaeger.perworldinventory.serialization.ItemSerializer.serialize(ItemSerializer.kt:49) ~[perworldinventory-kt-2.1.0.jar:?]
at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.serializeInventory(InventorySerializer.kt:43) ~[perworldinventory-kt-2.1.0.jar:?]
at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.serialize(PlayerSerializer.kt:33) ~[perworldinventory-kt-2.1.0.jar:?]
at me.ebonjaeger.perworldinventory.data.FlatFile.savePlayer(FlatFile.kt:44) ~[perworldinventory-kt-2.1.0.jar:?]
at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:59) ~[perworldinventory-kt-2.1.0.jar:?]
at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:20) ~[perworldinventory-kt-2.1.0.jar:?]
at me.ebonjaeger.perworldinventory.service.BukkitService$sam$java_lang_Runnable$0.run(BukkitService.kt) ~[perworldinventory-kt-2.1.0.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-eb3d921-2b93d83]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-eb3d921-2b93d83]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by EbonJaeger** [comment]
If you are not running 1.13, you need to be using the legacy jar for PWI. You can find that on the Releases page here on Github.

**Comment by NoopyyGaming** [comment]
I get the same message, and i'm running 1.9.4 server.

**Comment by EbonJaeger** [comment]
@NoopyyGaming please direct your attention to my comment right above yours. :)
