### ISSUE TITLE
StackTrace causes inventory loss

### ISSUE THREAD

**Issue by Eredrim** [EbonJaeger/perworldinventory-kt#72]
Hello,

Since the 2.0 version, I have sometimes a problem if a player can fly in a world and can't in another one. The player loses its inventory and the following stack trace is thrown : 
```
[Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to PerWorldInventory v2.1.0-legacy
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:719) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:537) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at com.earth2me.essentials.Teleport.now(Teleport.java:139) [EssentialsX-2.15.0.18.jar:?]
at com.earth2me.essentials.Teleport.teleport(Teleport.java:198) [EssentialsX-2.15.0.18.jar:?]
at com.earth2me.essentials.Teleport.warp(Teleport.java:255) [EssentialsX-2.15.0.18.jar:?]
at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:112) [EssentialsX-2.15.0.18.jar:?]
at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:47) [EssentialsX-2.15.0.18.jar:?]
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) [EssentialsX-2.15.0.18.jar:?]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:522) [EssentialsX-2.15.0.18.jar:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:435) [EssentialsX-2.15.0.18.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: Cannot make player fly if getAllowFlight() is false
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setFlying(CraftPlayer.java:1240) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
at me.ebonjaeger.perworldinventory.data.PlayerProperty$9.invoke(PlayerProperty.kt:28) ~[?:?]
at me.ebonjaeger.perworldinventory.data.PlayerProperty$9.invoke(PlayerProperty.kt:27) ~[?:?]
at me.ebonjaeger.perworldinventory.data.PlayerProperty$ValueAccessors.applyFromProfileToPlayer(PlayerProperty.kt:63) ~[?:?]
at me.ebonjaeger.perworldinventory.data.PlayerProperty.applyFromProfileToPlayerIfConfigured(PlayerProperty.kt:54) ~[?:?]
at me.ebonjaeger.perworldinventory.data.ProfileManager.applyToPlayer(ProfileManager.kt:125) ~[?:?]
at me.ebonjaeger.perworldinventory.data.ProfileManager.getPlayerData(ProfileManager.kt:100) ~[?:?]
at me.ebonjaeger.perworldinventory.listener.player.PlayerChangedWorldListener.onPlayerChangedWorld(PlayerChangedWorldListener.kt:106) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
... 29 more
```

The exception also appears with other plugins like essentialsX (not only with Multiverse).

**Comment by EbonJaeger** [comment]
@Eredrim Should be fixed with the above commits. Can you try this version and verify that this is indeed the case? Just rename the .zip to .jar, do not try to extract it.
[perworldinventory-kt-2.1.0-legacy.zip](https://github.com/EbonJaeger/perworldinventory-kt/files/2288148/perworldinventory-kt-2.1.0-legacy.zip)

**Comment by Eredrim** [comment]
It seems to work correctly. Thank you.

**Comment by EbonJaeger** [comment]
Thanks! Closed by https://github.com/EbonJaeger/perworldinventory-kt/commit/0666a3092e3a4d789d76f1564dac1a76987dad85
