### ISSUE TITLE
java.lang.NoSuchFieldError: PLAYER_HEAD

### ISSUE THREAD

**Issue by pLayEasZ** [EbonJaeger/perworldinventory-kt#73]
I have a problem when I send a user to another world, in the console I get this ..
PS: I'm using the latest version of the plugin

 [PerWorldInventory] Plugin PerWorldInventory v2.1.0 generated an exception while executing task 48
java.lang.NoSuchFieldError: PLAYER_HEAD
        at me.ebonjaeger.perworldinventory.serialization.ItemSerializer.serialize(ItemSerializer.kt:49) ~[?:?]
        at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.serializeInventory(InventorySerializer.kt:43) ~[?:?]
        at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.serializeAllInventories(InventorySerializer.kt:23) ~[?:?]
        at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.serialize(PlayerSerializer.kt:34) ~[?:?]
        at me.ebonjaeger.perworldinventory.data.FlatFile.savePlayer(FlatFile.kt:44) ~[?:?]
        at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:59) ~[?:?]
        at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:20) ~[?:?]
        at me.ebonjaeger.perworldinventory.service.BukkitService$sam$java_lang_Runnable$0.run(BukkitService.kt) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
>mv tp pLayEasZ survival
[10:46:13 WARN]: [PerWorldInventory] Plugin PerWorldInventory v2.1.0 generated an exception while executing task 50
java.lang.NoSuchFieldError: PLAYER_HEAD
        at me.ebonjaeger.perworldinventory.serialization.ItemSerializer.serialize(ItemSerializer.kt:49) ~[?:?]
        at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.serializeInventory(InventorySerializer.kt:43) ~[?:?]
        at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.serializeAllInventories(InventorySerializer.kt:23) ~[?:?]
        at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.serialize(PlayerSerializer.kt:34) ~[?:?]
        at me.ebonjaeger.perworldinventory.data.FlatFile.savePlayer(FlatFile.kt:44) ~[?:?]
        at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:59) ~[?:?]
        at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:20) ~[?:?]
        at me.ebonjaeger.perworldinventory.service.BukkitService$sam$java_lang_Runnable$0.run(BukkitService.kt) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by EbonJaeger** [comment]
You are not on 1.13, so you need to be using the legacy jar from the Github Releases page.
