### ISSUE TITLE
the following error 

### ISSUE THREAD

**Issue by Niko302** [EbonJaeger/perworldinventory-kt#82]
When I load in one of the mythicitems the following error happens:
```
[PerWorldInventory] Plugin PerWorldInventory v2.1.0 generated an exception while executing task 4892
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.bukkit.craftbukkit.v1_13_R2.attribute.CraftAttributeMap.fromMinecraft(CraftAttributeMap.java:51) ~[spigot1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.buildModifiers(CraftMetaItem.java:402) ~[spigot1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.<init>(CraftMetaItem.java:331) ~[spigot1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:498) ~[spigot1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:326) ~[spigot1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.inventory.ItemStack.serialize(ItemStack.java:436) ~[spigot1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:17) ~[spigot1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:47) ~[spigot1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1144) ~[?:1.8.0_181]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_181]
	at me.ebonjaeger.perworldinventory.serialization.ItemSerializer.serialize(ItemSerializer.kt:62) ~[?:?]
	at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.serializeInventory(InventorySerializer.kt:43) ~[?:?]
	at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.serializeAllInventories(InventorySerializer.kt:23) ~[?:?]
	at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.serialize(PlayerSerializer.kt:34) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.FlatFile.savePlayer(FlatFile.kt:44) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:59) ~[?:?]
	at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:20) ~[?:?]
	at me.ebonjaeger.perworldinventory.service.BukkitService$sam$java_lang_Runnable$0.run(BukkitService.kt) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot1.13.1.jar:git-Spigot-f6a273b-a639ae4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

```

**Comment by EbonJaeger** [comment]
Looks like that's the server itself failing to serialize an item; I doubt there's anything PWI can do about it. Can you link me to MythicItems so I can try to take a look at what it's doing? The closest thing I can find is MythicDrops.

**Comment by EbonJaeger** [comment]
@Niko302 is this issue still present on 2.2.1?
