### ISSUE TITLE
Error in console with PerWorldInventory

### ISSUE THREAD

**Issue by Spartan9802** [EbonJaeger/perworldinventory-kt#84]
Hi,
I just passed my version 2.0.1 which had some bugs, it happened that my players in freebuild exchange their inventories with survival, has version 2.2.0 it works perfectly for the moment but I have an error in the console.

Can you tell me where it came from?
My server is under spigot-1.8.8

```[16:18:55]

 [Craft Scheduler Thread - 35/WARN]: Exception in thread "Craft Scheduler Thread - 35" 
[16:18:55] [Craft Scheduler Thread - 35/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v2.2.0-legacy generated an exception while executing task 125947
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalAccessError: org/bukkit/craftbukkit/v1_8_R3/inventory/CraftMetaItem
	at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItemAccAccess.get(Unknown Source)
	at me.ebonjaeger.perworldinventory.libs.json.reader.BeansWriterASM.writeJSONString(BeansWriterASM.java:21)
	at me.ebonjaeger.perworldinventory.libs.json.JSONValue.writeJSONString(JSONValue.java:586)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter.writeJSONKV(JsonWriter.java:392)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$7.writeJSONString(JsonWriter.java:145)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$7.writeJSONString(JsonWriter.java:1)
	at me.ebonjaeger.perworldinventory.libs.json.JSONValue.writeJSONString(JSONValue.java:586)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter.writeJSONKV(JsonWriter.java:392)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$7.writeJSONString(JsonWriter.java:145)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$7.writeJSONString(JsonWriter.java:1)
	at me.ebonjaeger.perworldinventory.libs.json.JSONObject.writeJSON(JSONObject.java:186)
	at me.ebonjaeger.perworldinventory.libs.json.JSONObject.writeJSONString(JSONObject.java:200)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$2.writeJSONString(JsonWriter.java:83)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$2.writeJSONString(JsonWriter.java:1)
	at me.ebonjaeger.perworldinventory.libs.json.JSONValue.writeJSONString(JSONValue.java:586)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$5.writeJSONString(JsonWriter.java:113)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$5.writeJSONString(JsonWriter.java:1)
	at me.ebonjaeger.perworldinventory.libs.json.JSONArray.writeJSONString(JSONArray.java:75)
	at me.ebonjaeger.perworldinventory.libs.json.JSONArray.writeJSONString(JSONArray.java:131)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$2.writeJSONString(JsonWriter.java:83)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$2.writeJSONString(JsonWriter.java:1)
	at me.ebonjaeger.perworldinventory.libs.json.JSONValue.writeJSONString(JSONValue.java:586)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter.writeJSONKV(JsonWriter.java:392)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$7.writeJSONString(JsonWriter.java:145)
	at me.ebonjaeger.perworldinventory.libs.json.reader.JsonWriter$7.writeJSONString(JsonWriter.java:1)
	at me.ebonjaeger.perworldinventory.libs.json.JSONObject.writeJSON(JSONObject.java:186)
	at me.ebonjaeger.perworldinventory.libs.json.JSONObject.toJSONString(JSONObject.java:74)
	at me.ebonjaeger.perworldinventory.libs.json.JSONObject.toJSONString(JSONObject.java:264)
	at me.ebonjaeger.perworldinventory.data.FlatFile.savePlayer(FlatFile.kt:46)
	at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:59)
	at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:20)
	at me.ebonjaeger.perworldinventory.service.BukkitService$sam$java_lang_Runnable$0.run(BukkitService.kt)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more```

**Comment by EbonJaeger** [comment]
About to post the fix for that. Sorry about that.

**Comment by EbonJaeger** [comment]
Fixed in https://github.com/EbonJaeger/perworldinventory-kt/releases/tag/v2.2.1
