### ISSUE TITLE
Failed to deserialize item in inventory: [IllegalArgumentException] Unknown data format '3'.

### ISSUE THREAD

**Issue by Kikisito** [EbonJaeger/perworldinventory-kt#86]
Hello, I tried PerWorldInventory 2.2.1 in a server, and then had this error after trying it.

```java
[17:07:50 WARN]: [PerWorldInventory] Failed to deserialize item in inventory: [IllegalArgumentException] Unknown data format '3'.
[17:07:50 WARN]: java.lang.IllegalArgumentException: Unknown data format '3'.
[17:07:50 WARN]: at me.ebonjaeger.perworldinventory.serialization.ItemSerializer.deserialize(ItemSerializer.kt:106)
[17:07:50 WARN]: at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.deserialize(InventorySerializer.kt:69)
[17:07:50 WARN]: at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.deserialize(PlayerSerializer.kt:52)
[17:07:50 WARN]: at me.ebonjaeger.perworldinventory.data.FlatFile.getPlayer(FlatFile.kt:130)
[17:07:50 WARN]: at me.ebonjaeger.perworldinventory.data.ProfileManager.getPlayerData(ProfileManager.kt:97)
[17:07:50 WARN]: at me.ebonjaeger.perworldinventory.listener.player.PlayerChangedWorldListener.onPlayerChangedWorld(PlayerChangedWorldListener.kt:106)
[17:07:50 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:07:50 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:07:50 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:07:50 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[17:07:50 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[17:07:50 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:07:50 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[17:07:50 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[17:07:50 WARN]: at net.minecraft.server.v1_13_R2.PlayerList.moveToWorld(PlayerList.java:717)
[17:07:50 WARN]: at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:626)
[17:07:50 WARN]: at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:286)
[17:07:50 WARN]: at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215)
[17:07:50 WARN]: at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.teleport(SimpleSafeTTeleporter.java:335)
[17:07:50 WARN]: at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:163)
[17:07:50 WARN]: at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[17:07:50 WARN]: at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[17:07:50 WARN]: at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[17:07:50 WARN]: at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:919)
[17:07:50 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:07:50 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:07:50 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:695)
[17:07:50 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1644)
[17:07:50 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1479)
[17:07:50 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:07:50 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:07:50 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[17:07:50 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:07:50 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:07:50 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[17:07:50 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[17:07:50 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[17:07:50 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[17:07:50 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[17:07:50 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by EbonJaeger** [comment]
You did fully restart the server after uploading, right? Those line numbers don't match with the actual source line numbers.

**Comment by EbonJaeger** [comment]
Closing due to lack of response.
