### ISSUE TITLE
Error when converting from MV-I 2.5 SNAPSHOT 

### ISSUE THREAD

**Issue by ladspeak** [EbonJaeger/perworldinventory-kt#89]
Hi, I get this error when running /pwi convert

[10:42:01 ERROR]: [PerWorldInventory] [ACF] Exception in command: perworldinventory convert 

[10:42:01 ERROR]: [PerWorldInventory] [ACF] java.lang.reflect.InvocationTargetException

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at java.lang.reflect.Method.invoke(Method.java:498)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.RegisteredCommand.invoke(RegisteredCommand.java:147)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.BaseCommand.executeCommand(BaseCommand.java:650)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.BaseCommand.execute(BaseCommand.java:493)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.RootCommand.execute(RootCommand.java:67)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.acf.BukkitRootCommand.execute(BukkitRootCommand.java:62)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1761)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1565)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at java.lang.Thread.run(Thread.java:748)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] Caused by: java.lang.NoSuchMethodError: com.onarandombox.multiverseinventories.MultiverseInventories.getGroupManager()Lcom/onarandombox/multiverseinventories/api/GroupManager;

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.conversion.ConvertService.convertPlayers(ConvertService.kt:50)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.conversion.ConvertService.runConversion(ConvertService.kt:35)

[10:42:01 ERROR]: [PerWorldInventory] [ACF] 	at me.ebonjaeger.perworldinventory.command.ConvertCommand.onConvert(ConvertCommand.kt:40)

I have reinstalled PWI a few times since to see if it made a difference but I receive this error every time. The MV-I jar I am using is the latest dev build (https://ci.onarandombox.com/job/Multiverse-Inventories/) 

It should be noted that this server is running a recent build of Paper 1.13.2

**Comment by EbonJaeger** [comment]
Can you try it with this jar? Just rename the .zip to .jar, do not try to extract it.
[perworldinventory-kt-2.2.1.zip](https://github.com/EbonJaeger/perworldinventory-kt/files/2573102/perworldinventory-kt-2.2.1.zip)
