### ISSUE TITLE
NPE and failure on MI conversion

### ISSUE THREAD

**Issue by SlimeDog** [EbonJaeger/perworldinventory-kt#92]
Spigot 1.13.2 latest
Multiverse-Core 2.6.0-b738
Multiverse-Inventories 2.5.0-b444
perworldinventory-kt 2.2.1

> pwi convert

produced
```
[18:35:53 WARN]: Error while building configuration map.
java.lang.NullPointerException: null key in entry: null=1
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:172) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:248) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:1135) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1079) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1062) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.serialize(SerializationHelper.java:45) ~[Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.buildMap(SerializationHelper.java:71) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.serialize(SerializationHelper.java:46) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.buildMap(SerializationHelper.java:71) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.serialize(SerializationHelper.java:36) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.buildMap(SerializationHelper.java:71) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.serialize(SerializationHelper.java:36) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.buildMap(SerializationHelper.java:71) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.serialize(SerializationHelper.java:38) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.saveToString(JsonConfiguration.java:43) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:66) [spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at com.onarandombox.multiverseinventories.FlatFileProfileDataSource.processProfileWrite(FlatFileProfileDataSource.java:203) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.FlatFileProfileDataSource.access$300(FlatFileProfileDataSource.java:38) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.FlatFileProfileDataSource$FileWriter.call(FlatFileProfileDataSource.java:191) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.FlatFileProfileDataSource$FileWriter.call(FlatFileProfileDataSource.java:182) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[18:35:53 WARN]: Error while building configuration map.
java.lang.NullPointerException: null key in entry: null=1
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:172) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:248) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:1135) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1079) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1062) ~[spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.serialize(SerializationHelper.java:45) ~[Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.buildMap(SerializationHelper.java:71) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.serialize(SerializationHelper.java:46) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.buildMap(SerializationHelper.java:71) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.serialize(SerializationHelper.java:36) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.buildMap(SerializationHelper.java:71) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.serialize(SerializationHelper.java:36) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.buildMap(SerializationHelper.java:71) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.util.SerializationHelper.serialize(SerializationHelper.java:38) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.util.configuration.json.JsonConfiguration.saveToString(JsonConfiguration.java:43) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:66) [spigot-1.13.2.jar-2018-11-16-0044:git-Spigot-5696c83-b1d149c]
        at com.onarandombox.multiverseinventories.FlatFileProfileDataSource.processProfileWrite(FlatFileProfileDataSource.java:203) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.FlatFileProfileDataSource.access$300(FlatFileProfileDataSource.java:38) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.FlatFileProfileDataSource$FileWriter.call(FlatFileProfileDataSource.java:191) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at com.onarandombox.multiverseinventories.FlatFileProfileDataSource$FileWriter.call(FlatFileProfileDataSource.java:182) [Multiverse-Inventories-2.5.0-b444.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
Inventories were empty.

**Comment by EbonJaeger** [comment]
That looks to be an issue with MV-I trying to save someone's profile. Does not look like a PWI issue.

**Comment by SlimeDog** [comment]
Hmm. There is no explicit MV-I command to save inventories before /pwi convert. :(

**Comment by SlimeDog** [comment]
More important, the PWI inventories were empty after this process.

**Comment by SlimeDog** [comment]
Closed due to dev abandonment.
