### ISSUE TITLE
Could not pass event PlayerSpawnLocationEvent

### ISSUE THREAD

**Issue by kahiii** [EbonJaeger/perworldinventory-kt#96]
Using spigot 1.13.2 : Console send me this

```java
[13:49:01 ERROR]: Could not pass event PlayerSpawnLocationEvent to PerWorldInventory v2.2.         1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[         spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[sp         igot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [         spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [         spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:123) [spigot-1.13.2.         jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150) [spigot-1         .13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:54) [spigot-1         .13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231) [spigot         -1.13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120) [sp         igot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998) [spig         ot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spig         ot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spig         ot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [sp         igot-1.13.2.jar:git-Spigot-2474d93-e693496]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Doubl         e
        at me.ebonjaeger.perworldinventory.serialization.LocationSerializer.deserialize(Lo         cationSerializer.kt:38) ~[?:?]
        at me.ebonjaeger.perworldinventory.data.FlatFile.getLogout(FlatFile.kt:148) ~[?:?]
        at me.ebonjaeger.perworldinventory.listener.player.PlayerSpawnLocationListener.onP         layerSpawn(PlayerSpawnLocationListener.kt:31) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~         [?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.ja         va:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[         spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
        ... 13 more
```

**Comment by EbonJaeger** [comment]
Dupliate of #90
